package UNEducationProject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



/**
 *
 * @author marky
 */
public class ScienceGUI extends javax.swing.JFrame {

    
    public ScienceGUI() {
        initComponents();

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PlantsInfoButton = new javax.swing.JButton();
        HumanBodyInfoButton = new javax.swing.JButton();
        SpeedInfoButton = new javax.swing.JButton();
        LightInfoButton = new javax.swing.JButton();
        TheAtomInfoButton = new javax.swing.JButton();
        PHScaleInfoButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scienceInfoSwitch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PlantsTab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 255));

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        PlantsInfoButton.setBackground(new java.awt.Color(51, 204, 0));
        PlantsInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        PlantsInfoButton.setText("Plants");
        PlantsInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantsInfoButtonActionPerformed(evt);
            }
        });

        HumanBodyInfoButton.setBackground(new java.awt.Color(204, 0, 0));
        HumanBodyInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        HumanBodyInfoButton.setText("Human Body");
        HumanBodyInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanBodyInfoButtonActionPerformed(evt);
            }
        });

        SpeedInfoButton.setBackground(new java.awt.Color(255, 153, 0));
        SpeedInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        SpeedInfoButton.setText("Speed");
        SpeedInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedInfoButtonActionPerformed(evt);
            }
        });

        LightInfoButton.setBackground(new java.awt.Color(255, 0, 204));
        LightInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        LightInfoButton.setText("Light");
        LightInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LightInfoButtonActionPerformed(evt);
            }
        });

        TheAtomInfoButton.setBackground(new java.awt.Color(204, 204, 0));
        TheAtomInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        TheAtomInfoButton.setText("The Atom");
        TheAtomInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheAtomInfoButtonActionPerformed(evt);
            }
        });

        PHScaleInfoButton.setBackground(new java.awt.Color(51, 0, 204));
        PHScaleInfoButton.setForeground(new java.awt.Color(255, 255, 255));
        PHScaleInfoButton.setText("pH Scale");
        PHScaleInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHScaleInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlantsInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HumanBodyInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
            .addComponent(SpeedInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
            .addComponent(LightInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
            .addComponent(TheAtomInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
            .addComponent(PHScaleInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PlantsInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HumanBodyInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(SpeedInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LightInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PHScaleInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(TheAtomInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 0, 255));
        jPanel3.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lets learn about some fundamentals of Science!");

        scienceInfoSwitch.setBackground(new java.awt.Color(0, 255, 204));
        scienceInfoSwitch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scienceInfoSwitch.setText("QUIZ");
        scienceInfoSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceInfoSwitchActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Once finished click the 'QUIZ' Button to move on to the quiz.");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Click on the different panels on the left to learn more about the subjects.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(scienceInfoSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scienceInfoSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, 80));

        PlantsTab.setBackground(new java.awt.Color(153, 0, 255));
        PlantsTab.setForeground(new java.awt.Color(255, 255, 255));
        PlantsTab.setEnabled(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Plants can be found all over the world, and while they may be fundamentally different from us, as Humans\nand from the animals of the world, they are still alive. Like everything else alive, they need to eat and\nreproduce to continue to grow and spread, and that's what we'll be looking at for plants today.\n\nPlants 'eat' sunlight; and by eat, they absorb sunlight and turn it in to energy and sugars through a process \ncalled photosynthesis. Plants absorb more than sunlight for this process, they also need to absorb water\nfrom the soil, through roots, and CO2 from the air. Once a plant has all these ingredients it can start creating\nthe energy and sugars. This process happens inside the green part of the plant, due to a pigment called \nchlorophyll. This special pigment is why plants are green. Once the plant takes in the sunlight, water and CO2\nin to the chlorophyll, it produces glucose, a type of sugar, and oxygen. This process is why it is important to \nlook after forests and keep green spaces, removing to many plants means there won't be enough to filter \nthe CO2 in the air which is pretty bad for the enviroment.\n\nPlants also need to reproduce, and they do it asexually. This means that every plant can create more plants \nby themselves as they only need DNA from one parent. They do this with the help of pollinators, bees, \nbutterflies, etc. that will carry pollen produced by the plant to other plants to polinate them. Once seeds \ndevelop plants have found many different ways to spread them around. Through the wind, like dandelions,\nor animals, like fruit trees, or water, like the lotus.\n\n");
        jTextArea1.setBorder(null);
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        PlantsTab.addTab("tab1", jScrollPane1);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Speed is how we measure how fast an object is moving, or else can be described as the distance \ntraveled by an object in one unit of time. \n\nWe can calculate speed/distancee/time using the Speed Pyramid. \n\nThis is shown as:\n   D\nS    T\n\nD = Distance - how far the journey is. \nS = Speed - How fast the object is moving.\nT = How many units of time it takes.\n\nUsing two of these three, we can find the third. \n\nSpeed = Distance/Time.\nDistance = Speed*Time\nTime = Distance/Speed\n\n\n");
        jTextArea3.setBorder(null);
        jTextArea3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea3.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea3);

        PlantsTab.addTab("tab3", jScrollPane3);

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea5.setColumns(20);
        jTextArea5.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea5.setRows(5);
        jTextArea5.setText("The pH Scale is used to measure how acidic or basic something is. It does this on a scale of 1 - 14, where\n1 is as acidic as possible, 7 would be neutral and 14 would be as basic as possible. \n\nSome examples of acidic substances would be vinegar, lemon juice and sulfuric acid. \nSome basic examples are dish soap, bleach and sodium hydroxide. These substances can also be called\nalkaline. \nWhile, the most common example for a neutral substance would be water. \n\nOn the pH Scale, 1-6 (acids) is shown as varying degrees of red, where 1 is the most red and 6 is almost \nwhite. On the other end of the scale, 8-14 (bases) is shown as degrees of blue. 8 being the least amount\nof blue and 14 being very blue. 7 (neutral) is shown as true white. \n\nWe're able to test this using Litmus paper, in what is called a Litmus Test. In this test, part of the paper is \nplaced in the substance and will turn a shade of red/blue or remain white. This is used to check whether \nit is acidic or basic.\n");
        jTextArea5.setBorder(null);
        jTextArea5.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea5.setEnabled(false);
        jScrollPane5.setViewportView(jTextArea5);

        PlantsTab.addTab("tab5", jScrollPane5);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("The human body is a vast subject but here we'll only be covering the heart and the lungs.\n\nThe lungs breathe in and out air to absorb oxygen from it and expel CO2 from our bodies, and absorb \nenergy from the food we eat. it does this by using glucose, a nutrient, obtained from eating foods, such as \nbread. This process is called respiration.\n\nThe lungs are a complex organ made up of many parts that help carry oxygen from the air, through your \nmouth, into the lungs. There is the windpipe(or the trachea) which carries the air from the mouth to the \nlungs themselves. The Bronchus, which is the main 'branch' in your lungs, which carries the lungs to the \nbronchioles, which are smaller branches that then hold alveoli. Alveoli are where the respiration process \noccurs, creating the energy and extracting the oxygen. Once this oxygen is extracted it is then passed to \nthe heart where it is then shared with the rest of the body.\n\nThe heart is an important organ as it pumps blood around your body, carrying needed oxygen to different \nplaces. It is made of strong cardiac muscles that contract and relaxes,  every second of your life. Every \ntime it contract, it forces blood out of your heart and into your arteries. Every time is does this contraction,\na beat can be felt. This is called your pulse.\n\nArteries carry blood away from the heart, this blood is oxygenated. These blood vessels have thick walls \nand \nthe blood moving them is under high-pressue so it moves very fast. Veins carry blood to the heart, which is \ndeoxygenated. The blood presure is much lower than in arteries.  In veins there are valves, which prevent the \nblood from flowing backwards. The final blood vessels are called capillaries. These transport blood from \narteries to veins. These blood vessels have extremely thin walls which allow nutrients/oxygen/waste \nproducts to pass into and out of the capillaries, filtering the blood. ");
        jTextArea2.setBorder(null);
        jTextArea2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        PlantsTab.addTab("tab2", jScrollPane2);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setRows(5);
        jTextArea4.setText("Light is something that everyone experiences everyday. To understand it, we first need to understand \nthat it is a form of energy. This can be seen in plants, through photosynthesis and solar power, that \nwe've learned to harness from the sun's light through solar panels. \n\nThe sun is classed as a luminous object, which means it is an object that produces and and gives out\nit's own light. Some other examples of luminous objects would be a light bulb or a candle. In\ncomparisomn, non-luminous objects do not give off their own light. People, paper and many more\nobjects/animals are classed as non-luminous objects. \n\nLight is seen as white, but is actually made up of seven distinct colours, red, orange, yellow, green, \nblue, indigo and violet. The process of seperating white light into these colours is called dispersion.\nThese seven colours are known as the spectrum, and can be seen by using a prism in conjucture with \nwhite light. A natural example of this is a rainbow. \n\nLight is also how we have reflections. To have a reflection you need a plane surface in which the\nangle at which light comes in is the same as the angle that it leaves.  Mirrors are the most common\nexample of this.\n");
        jTextArea4.setBorder(null);
        jTextArea4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea4.setEnabled(false);
        jScrollPane4.setViewportView(jTextArea4);

        PlantsTab.addTab("tab4", jScrollPane4);

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(153, 0, 255));
        jTextArea6.setColumns(20);
        jTextArea6.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea6.setRows(5);
        jTextArea6.setText("The Periodic Table of Elements describes all known elements in the universe. \nThese elements act as the building blocks for all things, combining together to make molecules. \nAs an example a molecule of water is made up of the elements hydrogen and oxygen.\n\nThe Atom is the smallest particle of a chemical element that can exist. \nWater can also be represented by the chemical fomula H2O. \nThis represents the two atoms of hydrogen and one atom of oxygen that are combined in a specific \narrangement to make up a molecule of water.\n\nAll atoms are made up of three components: protons, electrons and neutrons. \nProtons are heavy, positively charged particles.\nElectrons are extremely light, negatively charged particles .\nNeutrons are heavy neutral particles. \n\nProtons and neutrons reside in the centre of the atom which is called the necleus while electrons orbit the \nnucleus in the electron cloud.\n\nOn the periodic table each element has an atomic number and a mass number.\nThe atomic number represents the number of protons in the nucleus for a singular atom of that elements. \nFor any atom without a charge, an atom has equal number of protons and electrons.\nThe mass number represents the sum of the number of protons and neutrons in the nucleus of an atom.\nOxygen has an atomic number of 8 and a mass number of 16.\nAs such a non charged atom of Oxygen would consist of 8 protons, 8 electrons and 8 neutrons.\n");
        jTextArea6.setBorder(null);
        jTextArea6.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextArea6.setEnabled(false);
        jScrollPane6.setViewportView(jTextArea6);

        PlantsTab.addTab("tab6", jScrollPane6);

        jPanel2.add(PlantsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 580, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HumanBodyInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanBodyInfoButtonActionPerformed
        PlantsTab.setSelectedIndex(3);
    }//GEN-LAST:event_HumanBodyInfoButtonActionPerformed

    private void SpeedInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedInfoButtonActionPerformed
        PlantsTab.setSelectedIndex(1);
    }//GEN-LAST:event_SpeedInfoButtonActionPerformed

    private void scienceInfoSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scienceInfoSwitchActionPerformed
        //new ScienceGUI().dispose();
        ScienceGUI frame1 = new ScienceGUI();
        ScienceQuizForm frame2 = new ScienceQuizForm();
        frame2.setVisible(true);
        frame1.setVisible(false);
        dispose();
    }//GEN-LAST:event_scienceInfoSwitchActionPerformed

    private void PlantsInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantsInfoButtonActionPerformed
        PlantsTab.setSelectedIndex(0);
    }//GEN-LAST:event_PlantsInfoButtonActionPerformed

    private void LightInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LightInfoButtonActionPerformed
        PlantsTab.setSelectedIndex(4);
    }//GEN-LAST:event_LightInfoButtonActionPerformed

    private void PHScaleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHScaleInfoButtonActionPerformed
        PlantsTab.setSelectedIndex(2);
    }//GEN-LAST:event_PHScaleInfoButtonActionPerformed

    private void TheAtomInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheAtomInfoButtonActionPerformed
        PlantsTab.setSelectedIndex(5);
    }//GEN-LAST:event_TheAtomInfoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScienceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScienceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScienceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScienceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScienceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HumanBodyInfoButton;
    private javax.swing.JButton LightInfoButton;
    private javax.swing.JButton PHScaleInfoButton;
    private javax.swing.JButton PlantsInfoButton;
    private javax.swing.JTabbedPane PlantsTab;
    private javax.swing.JButton SpeedInfoButton;
    private javax.swing.JButton TheAtomInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JButton scienceInfoSwitch;
    // End of variables declaration//GEN-END:variables
}
